version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    networks:
      - default

  olhoabertobackend:
    build:
      context: ./olhoabertobackend/dataSearcher
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    env_file:
      - ./olhoabertobackend/dataSearcher/.env
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - default

  # olhoabertofrontend:
  #   build:
  #     context: ./olhoabertofrontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./olhoabertofrontend:/app
  #     - /app/node_modules
  #   environment:
  #     NODE_ENV: development
  #   networks:
  #     - default

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   container_name: ngrok_tunnel
  #   env_file:
  #     - ./.env
  #   environment:
  #     NGROK_TUNNEL_PORT: 3000
  #     NGROK_TUNNEL_HOST: olhoabertofrontend
  #     NGROK_TUNNEL_PROTO: http
  #   command: "http olhoabertofrontend:3000"
  #   ports:
  #     - "4040:4040"
  #   depends_on:
  #     - olhoabertofrontend
  #   networks:
  #     - default

networks:
  default:
    driver: bridge
