version: "3.8"

services:
  zookeeper:
    network_mode: "host"
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    network_mode: "host"
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    depends_on:
      - zookeeper

  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  # news-watcher:
  #   network_mode: "host"
  #   build:
  #     context: ./newsWatcher
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production
  #     - KAFKA_BROKER=localhost:9092
  #   restart: unless-stopped
  #   depends_on:
  #     - kafka

volumes:
  redis_data:
    driver: local
